Great improvements Specify input file, specify output file, lint checking

diff --git a/beautify b/beautify
--- a/beautify
+++ b/beautify
@@ -1,7 +1,36 @@
 #!/bin/bash
 
-#php_beautifier -t -l "Pear() ListClassFunction() ArrayNested() NewLines(before=if:switch:T_COMMENT:T_CLASS:while,after='}')" -t1 $1
+INFILE="$1"
+OUTFILE="$2"
 
-#php_beautifier -d ~/bby/ -t -l "Pear() ListClassFunction() ArrayNested() BBY()" -t1 $1
-#php_beautifier -d ~/bby/ -t -l "Pear() ListClassFunction() ArrayNested() NewLines(before=if:switch:while:return:case:default) BBY()" -t1 $1
-php_beautifier -d ~/bin/ -l "beautify()" $1
+if [ -z "$INFILE" ]; then
+	INFILE="-"
+fi
+
+if [ -z "$OUTFILE" ]; then
+	OUTFILE="$INFILE"
+fi
+
+# Create temp file
+TEMPFILE="`mktemp`"
+
+# Beautify
+php_beautifier -d ~/bin/ -l "beautify()" "$INFILE" > "$TEMPFILE"
+
+# Lint check
+if ! php -l "$TEMPFILE" > /dev/null 2>&1; then
+	echo "Beautified code is invalid PHP" > /dev/stderr
+	echo " IN:  $INFILE" > /dev/stderr
+	echo "OUT:  $TEMPFILE" > /dev/stderr
+	exit 1
+fi
+
+if [ "$OUTFILE" == "-" ]; then
+	cat "$TEMPFILE"
+else
+	# Use cat to preserve file permissions
+	cat "$TEMPFILE" > "$OUTFILE"
+fi
+
+rm "$TEMPFILE"
+exit 0
